name: Scrape

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches: [main]  
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip3 install scrapy
      - name: Run Scraper
        run: scrapy crawl qa_practice -O qa.json
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: json output
          path: qa.json
